#### general settings
model: IRN
distortion: sr
scale: 4


#### datasets
datasets:
  train:
    name: DIV2K
    mode: LQGT
    batch_size: 8



#### network structures
network_G:
  which_model_G:
      subnet_type: DBNet
  in_nc: 3
  out_nc: 3
  block_num: [8, 8]
  scale: 4
  init: xavier



#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 2e-4
  beta1: 0.9
  beta2: 0.999
  epochs: 5000
  warmup_iter: -1  # no warm up

  lr_scheme: MultiStepLR
  lr_steps: [100000, 200000, 300000, 400000]
  lr_gamma: 0.5

  
  pixel_criterion_forw: l2
  pixel_criterion_back: l1

  manual_seed: 10
  
  val_freq: !!float 5e3

  lambda_fit_forw: 16.
  lambda_rec_back: 1
  lambda_ce_forw: 1
  weight_decay_G: !!float 1e-5
  gradient_clipping: 10
